export default class Weather {
  name: string = "Turkey";
  temp: number = 0;
}

export const weatherData: Weather[] = [
  {
    "name": "Ulaanbaatar/Khaan Intl, 1, MN",
    "temp": 9
  },
  {
    "name": "Christmas Isl Arpt, CX, AU",
    "temp": 26
  },
  {
    "name": "Singapore/Changi Intl, 4, SG",
    "temp": 26
  },
  {
    "name": "Salem Arpt, TN, IN",
    "temp": 31
  },
  {
    "name": "Kathmandu/Tribhuvan Intl, BA, NP",
    "temp": 23
  },
  {
    "name": "Hong Kong Intl, HK, CN",
    "temp": 26
  },
  {
    "name": "Kolkata/Bose Intl, WB, IN",
    "temp": 26
  },
  {
    "name": "Zangilan Intl, EZ, AZ",
    "temp": 18
  },
  {
    "name": "Nakhchivan Arpt, NX, AZ",
    "temp": 18
  },
  {
    "name": "Gyanca Intl, GY, AZ",
    "temp": 18
  },
  {
    "name": "Guadeloupe/Pitre Intl, --, GP",
    "temp": 28
  },
  {
    "name": "Le Lamentin/Cesaire Intl, FD, MQ",
    "temp": 28
  },
  {
    "name": "Cuzco/Astete Arpt, CU, PE",
    "temp": 5
  },
  {
    "name": "Cajamarca/Iglesias Arpt, CA, PE",
    "temp": 12
  },
  {
    "name": "Guarani Intl, 10, PY",
    "temp": 23
  },
  {
    "name": "Encarnacion/Gonzales Arpt, 7, PY",
    "temp": 23
  },
  {
    "name": "Asuncion/Pettriossi, 11, PY",
    "temp": 24
  },
  {
    "name": "Kiana/Baker Mem Arpt, AK, US",
    "temp": -1
  },
  {
    "name": "Sharjah Intl, SH, AE",
    "temp": 29
  },
  {
    "name": "Dubai/Al Maktoum Intl, DU, AE",
    "temp": 29
  },
  {
    "name": "Dubai Intl, DU, AE",
    "temp": 29
  },
  {
    "name": "La Tontouta Arpt, SU, NC",
    "temp": 21
  },
  {
    "name": "Hao/Tuamoto (MIL), TG, PF",
    "temp": 28
  },
  {
    "name": "Bora-Bora, LI, PF",
    "temp": 26
  },
  {
    "name": "Tubuai, TI, PF",
    "temp": 24
  },
  {
    "name": "Poprad/Tatry Arpt, NI, SK",
    "temp": 14
  },
  {
    "name": "Košice Intl, KI, SK",
    "temp": 15
  },
  {
    "name": "Bratislava/Ivanka Arpt, BL, SK",
    "temp": 14
  },
  {
    "name": "Budapest/Liszt Intl, BU, HU",
    "temp": 17
  },
  {
    "name": "Zadar Arpt, ZG, HR",
    "temp": 18
  },
  {
    "name": "Zagreb/Tudman Arpt, ZA, HR",
    "temp": 19
  },
  {
    "name": "Split Arpt, SP, HR",
    "temp": 19
  },
  {
    "name": "Rijeka Arpt, PR, HR",
    "temp": 17
  },
  {
    "name": "Pula Arpt, IS, HR",
    "temp": 17
  },
  {
    "name": "Osijek Arpt, OS, HR",
    "temp": 19
  },
  {
    "name": "Losinj Isl Arpt, LI, HR",
    "temp": 17
  },
  {
    "name": "Dubrovnik Arpt, DU, HR",
    "temp": 17
  },
  {
    "name": "Varna Intl, VA, BG",
    "temp": 12
  },
  {
    "name": "Sofia Intl, SO, BG",
    "temp": 19
  },
  {
    "name": "Plovdiv Arpt, PL, BG",
    "temp": 17
  },
  {
    "name": "Gorna Orechovista Arpt, LO, BG",
    "temp": 18
  },
  {
    "name": "Burgas Arpt, BU, BG",
    "temp": 12
  },
  {
    "name": "Roxboro/Person Cnty, NC, US",
    "temp": 6
  },
  {
    "name": "MIL, --, --",
    "temp": 18
  },
  {
    "name": "MIL, --, --",
    "temp": 17
  },
  {
    "name": "MIL, --, --",
    "temp": 18
  },
  {
    "name": "MIL, --, --",
    "temp": 21
  },
  {
    "name": "MIL, --, --",
    "temp": 24
  },
  {
    "name": "MIL, --, --",
    "temp": 24
  },
  {
    "name": "MIL, --, --",
    "temp": 16
  },
  {
    "name": "MIL, --, --",
    "temp": 19
  },
  {
    "name": "MIL, --, --",
    "temp": 19
  },
  {
    "name": "MIL, --, --",
    "temp": 19
  },
  {
    "name": "Louisburg/Franklin Cnty, NC, US",
    "temp": 8
  },
  {
    "name": "Smithfield/Johnston Rgnl, NC, US",
    "temp": 8
  },
  {
    "name": "Mississippi Canyon 474, MS, US",
    "temp": 22
  },
  {
    "name": "Erwin/Harnett Rgnl, NC, US",
    "temp": 9.1
  },
  {
    "name": "Jefferson/Ashe Cnty, NC, US",
    "temp": 11.4
  },
  {
    "name": "Fort Collins/N Colorado Rgnl, CO, US",
    "temp": -2
  },
  {
    "name": "Elizabethtown/Brown Fld, NC, US",
    "temp": 10.5
  },
  {
    "name": "Shelby/Cleveland Cnty, NC, US",
    "temp": 7
  },
  {
    "name": "Kenansville/Duplin Arpt, NC, US",
    "temp": 9
  },
  {
    "name": "Whiteville/Columbus Cnty, NC, US",
    "temp": 10.3
  },
  {
    "name": "Green Canyon Blk 763, LA, US",
    "temp": 24
  },
  {
    "name": "Leonardtown/St Marys, MD, US",
    "temp": 8
  },
  {
    "name": "Sylva/Jackson Cnty, NC, US",
    "temp": 7.7
  },
  {
    "name": "Franklin/Macon Cnty, NC, US",
    "temp": 3
  },
  {
    "name": "Kigali Intl, KI, RW",
    "temp": 23
  },
  {
    "name": "Cairo Intl, QH, EG",
    "temp": 28
  },
  {
    "name": "Antananarivo/Ivato Intl, T, MG",
    "temp": 28
  },
  {
    "name": "Dzaoudzi/Pamandzi Intl, MA, KM",
    "temp": 30
  },
  {
    "name": "Ringsted Arpt, --, DK",
    "temp": 11
  },
  {
    "name": "Abidjan/Boigny Intl, AB, CI",
    "temp": 31
  },
  {
    "name": "Swift Current Arpt, SK, CA",
    "temp": -4
  },
  {
    "name": "Pristina Intl, PR, KV",
    "temp": 19
  },
  {
    "name": "Napakiak Arpt, AK, US",
    "temp": -4
  },
  {
    "name": "Southport/Cape Fear Rgnl, NC, US",
    "temp": 13
  },
  {
    "name": "Sidney/Carr Fld, NE, US",
    "temp": -0.6
  },
  {
    "name": "Andrews/W Carolina Rgnl, NC, US",
    "temp": 5.1
  },
  {
    "name": "Boscobel Arpt, WI, US",
    "temp": 11.7
  },
  {
    "name": "Logan/Cache Arpt, UT, US",
    "temp": -1.7
  },
  {
    "name": "Fort Meade/Tipton Fld, MD, US",
    "temp": 2
  },
  {
    "name": "New Iberia/Acadiana Rgnl, LA, US",
    "temp": 22.8
  },
  {
    "name": "Wadesboro/Anson Cnty, NC, US",
    "temp": 6.9
  },
  {
    "name": "Pond Inlet Arpt, NU, CA",
    "temp": -25
  },
  {
    "name": "Shaktoolik Arpt, AK, US",
    "temp": -1
  },
  {
    "name": "Anvik Arpt, AK, US",
    "temp": -1
  },
  {
    "name": "Sturgeon Bay/Door Cnty, WI, US",
    "temp": 6
  },
  {
    "name": "Spencer Muni, IA, US",
    "temp": 6.1
  },
  {
    "name": "Rochester Intl, MN, US",
    "temp": 11.7
  },
  {
    "name": "Lone Rock/Tri Cnty Rgnl, WI, US",
    "temp": 11.1
  },
  {
    "name": "Pickle Lake Arpt, ON, CA",
    "temp": 0
  },
  {
    "name": "Bethel Arpt, AK, US",
    "temp": -5
  },
  {
    "name": "Norfolk/Stefan Mem, NE, US",
    "temp": 6.1
  },
  {
    "name": "Harbor Springs Arpt, MI, US",
    "temp": 10
  },
  {
    "name": "Lamoni Muni, IA, US",
    "temp": 16.1
  },
  {
    "name": "Hill City Muni, KS, US",
    "temp": 5
  },
  {
    "name": "Churchill Falls Arpt, NL, CA",
    "temp": -4
  },
  {
    "name": "Kaneohe Bay (MCAS), HI, US",
    "temp": 23.9
  },
  {
    "name": "King Cove Arpt, AK, US",
    "temp": 2
  },
  {
    "name": "St Michael Arpt, AK, US",
    "temp": -3
  },
  {
    "name": "Santa Rosa/Schulz Arpt, CA, US",
    "temp": 8.3
  },
  {
    "name": "McAllen/Miller Intl, TX, US",
    "temp": 24.4
  },
  {
    "name": "Cortez/Montezuma Cnt, CO, US",
    "temp": 1.1
  },
  {
    "name": "Schefferville Arpt, QC, CA",
    "temp": -5
  },
  {
    "name": "Burwash Arpt, YT, CA",
    "temp": 1
  },
  {
    "name": "Pavlodar Arpt, PA, KZ",
    "temp": 0
  },
  {
    "name": "Guam/Andersen AFB, --, GU",
    "temp": 26
  },
  {
    "name": "Unalakleet Arpt, AK, US",
    "temp": -2
  },
  {
    "name": "Ft Richardson/Bryant AAF, AK, US",
    "temp": 5
  },
  {
    "name": "Lahore/Iqbal Intl, PB, PK",
    "temp": 36
  },
  {
    "name": "Stevensville/Bay Bridge Arpt, MD, US",
    "temp": 10.8
  },
  {
    "name": "Albemarle/Stanly Cnty, NC, US",
    "temp": 6.5
  },
  {
    "name": "Wilkesboro/Wilkes Cnty, NC, US",
    "temp": 6
  },
  {
    "name": "Sanford/Lee Cnty, NC, US",
    "temp": 5.5
  },
  {
    "name": "Statesville Muni, NC, US",
    "temp": 7.3
  },
  {
    "name": "Eden/Shiloh Arpt, NC, US",
    "temp": 5.5
  },
  {
    "name": "Siler City Muni, NC, US",
    "temp": 7
  },
  {
    "name": "Rawlins Muni, WY, US",
    "temp": -6.1
  },
  {
    "name": "Salisbury/Rowan Cnty, NC, US",
    "temp": 7.5
  },
  {
    "name": "Rockingham/Richmond Cnty, NC, US",
    "temp": 10.2
  },
  {
    "name": "Greenville/Pitt Arpt, NC, US",
    "temp": 10
  },
  {
    "name": "Currituck Cnty, NC, US",
    "temp": 9.2
  },
  {
    "name": "Washington/Warren Arpt, NC, US",
    "temp": 8.4
  },
  {
    "name": "Mt Airy/Surry Cnty, NC, US",
    "temp": 7
  },
  {
    "name": "Morganton/Foothills Rgnl, NC, US",
    "temp": 5.5
  },
  {
    "name": "Manteo/Dare Cnty, NC, US",
    "temp": 13.5
  },
  {
    "name": "Minot Intl, ND, US",
    "temp": -2.2
  },
  {
    "name": "Williamston/Martin Cnty, NC, US",
    "temp": 8.3
  },
  {
    "name": "Jonesboro Muni, AR, US",
    "temp": 20.6
  },
  {
    "name": "Halifax/Northampton Rgnl, NC, US",
    "temp": 5
  },
  {
    "name": "Lincolnton/Lincoln Cnty, NC, US",
    "temp": 5.5
  },
  {
    "name": "Mackall(AAF), NC, US",
    "temp": 8
  },
  {
    "name": "Asheboro Muni, NC, US",
    "temp": 10.7
  },
  {
    "name": "Goldsboro/Wayne Muni, NC, US",
    "temp": 8.4
  },
  {
    "name": "Gurden Banks 668, TX, US",
    "temp": 24
  },
  {
    "name": "Rutherfordton/Marchman Fld, NC, US",
    "temp": 6
  },
  {
    "name": "Los Angeles Downtown, CA, US",
    "temp": 13
  },
  {
    "name": "Kill Devil Hill/First Flight Arpt, NC, US",
    "temp": 12.9
  },
  {
    "name": "Lexington/Davidson Cnty, NC, US",
    "temp": 8.7
  },
  {
    "name": "Tarboro/Edgecombe Arpt, NC, US",
    "temp": 7.9
  },
  {
    "name": "Edenton/Northeast Rgnl, NC, US",
    "temp": 10.2
  },
  {
    "name": "Clinton/Sampson Cnty, NC, US",
    "temp": 10.9
  },
  {
    "name": "College Park Arpt, MD, US",
    "temp": 4.5
  },
  {
    "name": "Cambridge/Dorchester Rgnl, MD, US",
    "temp": 7
  },
  {
    "name": "Cumberland Arpt, MD, US",
    "temp": 4.6
  },
  {
    "name": "Ahoskie/Tri Cnty, NC, US",
    "temp": 7.4
  },
  {
    "name": "Wallace/Henderson Fld, NC, US",
    "temp": 9.1
  },
  {
    "name": "AFA/Bullseye Astrp, CO, US",
    "temp": -1
  },
  {
    "name": "Oakland/Garrett Cnty, MD, US",
    "temp": 12
  },
  {
    "name": "India(Palermo), ND, US",
    "temp": -1
  },
  {
    "name": "Echo(Ryder), ND, US",
    "temp": -5
  },
  {
    "name": "Churchville/Harford Cnty, MD, US",
    "temp": 8.1
  },
  {
    "name": "Illesheim Arpt(AAF), BY, DE",
    "temp": 11
  },
  {
    "name": "Grafenwohr(AFB), BY, DE",
    "temp": 8
  },
  {
    "name": "Katterbach Arpt(MIL), BY, DE",
    "temp": 9
  },
  {
    "name": "Woensdrecht(AB), NB, NL",
    "temp": 16
  },
  {
    "name": "Vlieland Island, FR, NL",
    "temp": 11
  },
  {
    "name": "Volkel Arpt(AFB), NB, NL",
    "temp": 11
  },
  {
    "name": "Goeree Le Sea, --, NL",
    "temp": 11
  },
  {
    "name": "Euro Platform, --, NL",
    "temp": 9
  },
  {
    "name": "Rotterdam/The Hague Arpt, ZH, NL",
    "temp": 14
  },
  {
    "name": "P11-B Sea, --, NL",
    "temp": 9
  },
  {
    "name": "L9-FF-1 Sea, --, NL",
    "temp": 9
  },
  {
    "name": "AWG-1 Sea, --, NL",
    "temp": 8
  },
  {
    "name": "Leeuwarden Arpt(AB), FR, NL",
    "temp": 11
  },
  {
    "name": "Lelystad Arpt, FL, NL",
    "temp": 11
  },
  {
    "name": "K14-FA-1C Sea, --, NL",
    "temp": 9
  },
  {
    "name": "Den Helder Arpt, NH, NL",
    "temp": 12
  },
  {
    "name": "K14-A Sea, --, NL",
    "temp": 9
  },
  {
    "name": "J6-A Sea, --, NL",
    "temp": 9
  },
  {
    "name": "Buitengaats, --, NL",
    "temp": 9
  },
  {
    "name": "Gilze-Rijen(AB), NB, NL",
    "temp": 13
  },
  {
    "name": "Groningen Arpt, DR, NL",
    "temp": 11
  },
  {
    "name": "F3-FB-1 Sea, --, NL",
    "temp": 8
  },
  {
    "name": "Eindhoven Arpt, NB, NL",
    "temp": 12
  },
  {
    "name": "D15-FA-1 Sea, --, NL",
    "temp": 9
  },
  {
    "name": "Deelen(AB), GE, NL",
    "temp": 12
  },
  {
    "name": "Maastricht/Aachen Arpt, LI, NL",
    "temp": 11
  },
  {
    "name": "Amsterdam/Schiphol Arpt, NH, NL",
    "temp": 13
  },
  {
    "name": "A12-CPP Sea, --, NL",
    "temp": 8
  },
  {
    "name": "Sandy Lake Arpt, ON, CA",
    "temp": -2
  },
  {
    "name": "Muskoka Arpt, ON, CA",
    "temp": 6
  },
  {
    "name": "St Paul Island Arpt, AK, US",
    "temp": 0.6
  },
  {
    "name": "Cape Romanzof Arpt, AK, US",
    "temp": -7
  },
  {
    "name": "León Arpt, CL, ES",
    "temp": 9
  },
  {
    "name": "Russellville Rgnl, AR, US",
    "temp": 20.6
  },
  {
    "name": "Ozark/Cairns AAF, AL, US",
    "temp": 10
  },
  {
    "name": "Saginaw Intl, MI, US",
    "temp": 12.8
  },
  {
    "name": "Leadville/Lake Cnty, CO, US",
    "temp": -4.4
  },
  {
    "name": "Ironwood/Iron Cnty, MI, US",
    "temp": 5
  },
  {
    "name": "Big Piney Arpt, WY, US",
    "temp": -6.7
  },
  {
    "name": "Sandspit Arpt, BC, CA",
    "temp": 9
  },
  {
    "name": "Moosonee Arpt, ON, CA",
    "temp": -4
  },
  {
    "name": "Cylde River Arpt, NU, CA",
    "temp": -18
  },
  {
    "name": "Sparta/Ft McCoy Arpt, WI, US",
    "temp": 12
  },
  {
    "name": "Chippewa Cnty Intl, MI, US",
    "temp": 5
  },
  {
    "name": "Ashland/Kennedy Mem Arpt, WI, US",
    "temp": 6.1
  },
  {
    "name": "Nipawin(AUTO), SK, CA",
    "temp": -5
  },
  {
    "name": "Wake Island Arpt, WQ, UM",
    "temp": 26
  },
  {
    "name": "Noorvik/Curtis Mem, AK, US",
    "temp": -2
  },
  {
    "name": "Riverton Rgnl, WY, US",
    "temp": -5
  },
  {
    "name": "Ellsworth AFB, SD, US",
    "temp": 0
  },
  {
    "name": "Menominee/Twin Cnty, MI, US",
    "temp": 8
  },
  {
    "name": "Livermore Muni, CA, US",
    "temp": 11.7
  },
  {
    "name": "La Crosse Muni, WI, US",
    "temp": 13.3
  },
  {
    "name": "Lander/Hunt Fld, WY, US",
    "temp": -5
  },
  {
    "name": "Burlington/Kit Carson Cnty, CO, US",
    "temp": 0.6
  },
  {
    "name": "Grand Island Rgnl, NE, US",
    "temp": 6.7
  },
  {
    "name": "Grand Canyon Park Arpt, AZ, US",
    "temp": 0.6
  },
  {
    "name": "Topeka/Forbes Fld, KS, US",
    "temp": 13.9
  },
  {
    "name": "Mount Vernon/Knox Cnty, OH, US",
    "temp": 14
  },
  {
    "name": "Big Trout Lake Arpt, ON, CA",
    "temp": -8
  },
  {
    "name": "Red Lake Arpt, ON, CA",
    "temp": 1
  },
  {
    "name": "Peterborough Muni, ON, CA",
    "temp": 2
  },
  {
    "name": "Akhiok Arpt, AK, US",
    "temp": 1
  },
  {
    "name": "McMurdo/Williams Fld, NZ, AQ",
    "temp": -21.9
  },
  {
    "name": "Santiago Arpt, GA, ES",
    "temp": 11
  },
  {
    "name": "Schell AFP, AL, US",
    "temp": 11
  },
  {
    "name": "Provo Muni, UT, US",
    "temp": 1
  },
  {
    "name": "Houghton Cnty Mem, MI, US",
    "temp": 4.4
  },
  {
    "name": "Crestview/Sikes Arpt, FL, US",
    "temp": 8.3
  },
  {
    "name": "Bozeman/Gallatin Fld, MT, US",
    "temp": -7.2
  },
  {
    "name": "Napa Cnty Arpt, CA, US",
    "temp": 10.6
  },
  {
    "name": "Norway House Arpt, MB, CA",
    "temp": -10
  },
  {
    "name": "Kwajalein/Bucholz AA, L, MH",
    "temp": 26.9
  },
  {
    "name": "Atqasuk/Burnell Mem, AK, US",
    "temp": -12
  },
  {
    "name": "Buckland Arpt, AK, US",
    "temp": -7
  },
  {
    "name": "Skopje Intl, IL, MK",
    "temp": 25
  },
  {
    "name": "Ohrid Arpt, DB, MK",
    "temp": 16
  },
  {
    "name": "Istanbul Arpt, IS, TR",
    "temp": 10
  },
  {
    "name": "Istanbul/Gokcen Intl, KO, TR",
    "temp": 19
  },
  {
    "name": "Milas-Bodrun Arpt, MU, TR",
    "temp": 26
  },
  {
    "name": "Isparta/Demirel Arpt, IZ, TR",
    "temp": 26
  },
  {
    "name": "Tarsus/Cukurova Intl, ME, TR",
    "temp": 29
  },
  {
    "name": "Sanliurfa Gap Intl, SA, TR",
    "temp": 23
  },
  {
    "name": "Batman Arpt, SI, TR",
    "temp": 23
  },
  {
    "name": "Trabzon Arpt, TR, TR",
    "temp": 13
  },
  {
    "name": "Erzurum Intl, EZ, TR",
    "temp": 13
  },
  {
    "name": "Diyarbakir Arpt, DI, TR",
    "temp": 22
  },
  {
    "name": "Corlu Arpt, TE, TR",
    "temp": 19
  },
  {
    "name": "Dalaman Arpt, MU, TR",
    "temp": 21
  },
  {
    "name": "Bursa/Yenisehir Arpt, BR, TR",
    "temp": 27
  },
  {
    "name": "Izmir/Menderes Arpt, IZ, TR",
    "temp": 28
  },
  {
    "name": "Istanbul/Ataturk Intl, IS, TR",
    "temp": 18
  },
  {
    "name": "Nevsehir Arpt, NE, TR",
    "temp": 25
  },
  {
    "name": "Kayseri Intl, KA, TR",
    "temp": 22
  },
  {
    "name": "Malatya Arpt, MA, TR",
    "temp": 23
  },
  {
    "name": "Gaziantep Arpt, GA, TR",
    "temp": 25
  },
  {
    "name": "Antalya Arpt, AN, TR",
    "temp": 21
  },
  {
    "name": "Adana/Incirlik(AB), AD, TR",
    "temp": 30
  },
  {
    "name": "Adana Arpt, AD, TR",
    "temp": 30
  },
  {
    "name": "Ankara/Esenboğa Intl, AN, TR",
    "temp": 24
  },
  {
    "name": "Samedan Arpt, GR, CH",
    "temp": 9
  },
  {
    "name": "St Gallen/Altenrhein Arpt, SG, CH",
    "temp": 9
  },
  {
    "name": "Locarno Arpt, TI, CH",
    "temp": 16
  },
  {
    "name": "Zürich Intl Arpt, ZH, CH",
    "temp": 8
  },
  {
    "name": "Grenchen Arpt, SO, CH",
    "temp": 10
  },
  {
    "name": "Buochs Arpt, NW, CH",
    "temp": 10
  },
  {
    "name": "Bern Arpt, BE, CH",
    "temp": 11
  },
  {
    "name": "Lugano Arpt, TI, CH",
    "temp": 17
  },
  {
    "name": "Payerne Arpt(MIL), VD, CH",
    "temp": 12
  },
  {
    "name": "Meiringen Arpt, BE, CH",
    "temp": 10
  },
  {
    "name": "Emmen Arpt(MIL), LU, CH",
    "temp": 10
  },
  {
    "name": "Dübendorf Arpt(MIL), ZH, CH",
    "temp": 8
  },
  {
    "name": "Alpnach Arpt(MIL), OW, CH",
    "temp": 10
  },
  {
    "name": "Sion Arpt, VS, CH",
    "temp": 10
  },
  {
    "name": "Geneva/Cointrin Arpt, GE, CH",
    "temp": 13
  },
  {
    "name": "Les Eplatures Arpt, NE, CH",
    "temp": 5
  },
  {
    "name": "Zeltweg Arpt(AB), ST, AT",
    "temp": 9
  },
  {
    "name": "Vienna Intl, NE, AT",
    "temp": 13
  },
  {
    "name": "Salzburg/Mozart Arpt, SA, AT",
    "temp": 9
  },
  {
    "name": "Linz Arpt, OB, AT",
    "temp": 10
  },
  {
    "name": "Klagenfurt Arpt, KA, AT",
    "temp": 11
  },
  {
    "name": "Innsbruck Arpt, TI, AT",
    "temp": 12
  },
  {
    "name": "Graz Arpt, ST, AT",
    "temp": 12
  },
  {
    "name": "Tel Aviv/Ben Gurion Arpt, C, IL",
    "temp": 31
  },
  {
    "name": "Perugia/Francesco Arpt, PG, IT",
    "temp": 15
  },
  {
    "name": "Florence/Peretola Arpt, FI, IT",
    "temp": 14
  },
  {
    "name": "Naples Intl, NA, IT",
    "temp": 16
  },
  {
    "name": "Rome/Fiumicino, RM, IT",
    "temp": 18
  },
  {
    "name": "Rome/Ciampino Arpt, RM, IT",
    "temp": 16
  },
  {
    "name": "Venice/Polo Arpt, VE, IT",
    "temp": 17
  },
  {
    "name": "Falconara/Ancona Arpt, AN, IT",
    "temp": 16
  },
  {
    "name": "Verona Arpt, TO, IT",
    "temp": 16
  },
  {
    "name": "Rimini/Miramare Arpt, RN, IT",
    "temp": 17
  },
  {
    "name": "Trieste Airport, CU, IT",
    "temp": 17
  },
  {
    "name": "Brescia Arpt, BS, IT",
    "temp": 18
  },
  {
    "name": "Treviso Arpt, TV, IT",
    "temp": 18
  },
  {
    "name": "Bologna/Marconi Arpt, BO, IT",
    "temp": 17
  },
  {
    "name": "Cuneo/Levaldigi Arpt, CN, IT",
    "temp": 18
  },
  {
    "name": "Aosta Valley Arpt, AO, IT",
    "temp": 17
  },
  {
    "name": "Milan/Linate Arpt, MI, IT",
    "temp": 17
  },
  {
    "name": "Genoa/Colombo Arpt, GE, IT",
    "temp": 15
  },
  {
    "name": "Torino/Caselle Arpt, TO, IT",
    "temp": 17
  },
  {
    "name": "Bergamo/Orio Seno Arpt, BG, IT",
    "temp": 16
  },
  {
    "name": "Milan/Malpensa Arpt, MI, IT",
    "temp": 17
  },
  {
    "name": "Olbia/Costa Smeralda Arpt, OT, IT",
    "temp": 20
  },
  {
    "name": "Cagliari/Elmas Arpt, CA, IT",
    "temp": 19
  },
  {
    "name": "Alghero/Fertilia Arpt, SS, IT",
    "temp": 19
  },
  {
    "name": "Reggio Calabria Arpt, RE, IT",
    "temp": 20
  },
  {
    "name": "Palermo Arpt, PA, IT",
    "temp": 17
  },
  {
    "name": "Pantelleria Arpt, TP, IT",
    "temp": 19
  },
  {
    "name": "Lampedusa Island Arpt, AG, IT",
    "temp": 19
  },
  {
    "name": "Catania/Fontanarossa Arpt, CT, IT",
    "temp": 22
  },
  {
    "name": "Comiso Arpt, RG, IT",
    "temp": 19
  },
  {
    "name": "Lamezia Terme Arpt, CA, IT",
    "temp": 16
  },
  {
    "name": "Brindisi/Casale Arpt, PU, IT",
    "temp": 18
  },
  {
    "name": "Pescara/Abruzzo Arpt, AB, IT",
    "temp": 17
  },
  {
    "name": "Bari/Palese Arpt, PU, IT",
    "temp": 18
  },
  {
    "name": "Zakinthos/Salomos Arpt, J, GR",
    "temp": 22
  },
  {
    "name": "Thessaloniki Intl, A, GR",
    "temp": 21
  },
  {
    "name": "Santorini Isl Aprt, K, GR",
    "temp": 23
  },
  {
    "name": "Skiathos Isl Arpt, K, GR",
    "temp": 18
  },
  {
    "name": "Souda Bay/Chania Intl, M, GR",
    "temp": 23
  },
  {
    "name": "Araxos Arpt, J, GR",
    "temp": 20
  },
  {
    "name": "Rhodes/Diagoras Arpt, K, GR",
    "temp": 20
  },
  {
    "name": "Preveza/Aktion Arpt, G, GR",
    "temp": 20
  },
  {
    "name": "Paros/Kratikos Arpt, K, GR",
    "temp": 21
  },
  {
    "name": "Mitilini Arpt, K, GR",
    "temp": 26
  },
  {
    "name": "Mykonos Arpt, K, GR",
    "temp": 21
  },
  {
    "name": "Limnos Island Arpt, K, GR",
    "temp": 19
  },
  {
    "name": "Kozani/Filippos Arpt, C, GR",
    "temp": 20
  },
  {
    "name": "Kavala Intl, A, GR",
    "temp": 21
  },
  {
    "name": "Corfu/Kapodistinas Arpt, L, GR",
    "temp": 20
  },
  {
    "name": "Karpathos Isl Arpt, M, GR",
    "temp": 21
  },
  {
    "name": "Kos Arpt, K, GR",
    "temp": 22
  },
  {
    "name": "Kalamata Arpt, J, GR",
    "temp": 24
  },
  {
    "name": "Cephalonia Arpt, F, GR",
    "temp": 19
  },
  {
    "name": "Iraklion Intl, M, GR",
    "temp": 21
  },
  {
    "name": "Ioannina Arpt, D, GR",
    "temp": 20
  },
  {
    "name": "Elefsis(AB), I, GR",
    "temp": 27
  },
  {
    "name": "Nea Anchialos Arpt(MIL), E, GR",
    "temp": 24
  },
  {
    "name": "Athens/Venizelos Intl, I, GR",
    "temp": 25
  },
  {
    "name": "Alexandroupolis/Dimokritos Arpt, A, GR",
    "temp": 23
  },
  {
    "name": "Andravida Arpt, J, GR",
    "temp": 20
  },
  {
    "name": "Akrotiri Arpt(RAF), LE, CY",
    "temp": 26
  },
  {
    "name": "Ercan Arpt, LE, CY",
    "temp": 31
  },
  {
    "name": "Tirana Intl, TR, AL",
    "temp": 20
  },
  {
    "name": "Worland Muni, WY, US",
    "temp": -3.3
  },
  {
    "name": "Columbus/Bolton Fld, OH, US",
    "temp": 13
  },
  {
    "name": "San Bernardino Intl, CA, US",
    "temp": 11
  },
  {
    "name": "MIL, --, --",
    "temp": 17
  },
  {
    "name": "MIL, --, --",
    "temp": 18
  },
  {
    "name": "MIL, --, --",
    "temp": 21
  },
  {
    "name": "MIL, --, --",
    "temp": 21
  },
  {
    "name": "MIL, --, --",
    "temp": 18
  },
  {
    "name": "MIL, --, --",
    "temp": 15
  },
  {
    "name": "Pope AAF, NC, US",
    "temp": 9
  },
  {
    "name": "Poplar Muni, MT, US",
    "temp": -1
  },
  {
    "name": "Houston/Pearland Rgnl, TX, US",
    "temp": 22.8
  },
  {
    "name": "Lincoln Rgnl, CA, US",
    "temp": 11
  },
  {
    "name": "Sallisaw Muni, OK, US",
    "temp": 21
  },
  {
    "name": "Gulf of Mexino, LA, US",
    "temp": 25
  },
  {
    "name": "Oxford-Henderson Arpt, NC, US",
    "temp": 8.3
  },
  {
    "name": "Blytheville Muni, AR, US",
    "temp": 21.1
  },
  {
    "name": "Mississippi Canyon 650, LA, US",
    "temp": 0
  },
  {
    "name": "Westminster/Carroll Cnty Rgnl, MD, US",
    "temp": 9
  },
  {
    "name": "Douglas/Converse Cnty, WY, US",
    "temp": -3.3
  },
  {
    "name": "Columbus AFB, MS, US",
    "temp": 17
  },
  {
    "name": "Milbank Muni, SD, US",
    "temp": 5
  },
  {
    "name": "Owyhee Arpt, NV, US",
    "temp": -2
  },
  {
    "name": "Vilnius Intl, VL, LT",
    "temp": 23
  },
  {
    "name": "Šiauliai Intl, SA, LT",
    "temp": 26
  },
  {
    "name": "Palanga Intl, KL, LT",
    "temp": 21
  },
  {
    "name": "Kaunas Arpt, KI, LT",
    "temp": 25
  },
  {
    "name": "Ventpils Arpt, VS, LV",
    "temp": 23
  },
  {
    "name": "Riga Intl, RG, LV",
    "temp": 27
  },
  {
    "name": "Liepaja Intl, LP, LV",
    "temp": 20
  },
  {
    "name": "Lielvarde Arpt, RG, LV",
    "temp": 27
  },
  {
    "name": "Meppen(MIL), NI, DE",
    "temp": 10
  },
  {
    "name": "Nueburg/Donau Arpt, BY, DE",
    "temp": 10
  },
  {
    "name": "Lechfeld (AFB), BY, DE",
    "temp": 10
  },
  {
    "name": "Ingolstadt-Manching Arpt, BY, DE",
    "temp": 10
  },
  {
    "name": "Holzdorf Arpt(MIL), BR, DE",
    "temp": 11
  },
  {
    "name": "Buechel Arpt, RP, DE",
    "temp": 6
  },
  {
    "name": "Wunstorf (AFB), NI, DE",
    "temp": 9
  },
  {
    "name": "Wittmundhaven Arpt, NI, DE",
    "temp": 9
  },
  {
    "name": "Schleswig(NAVY), SH, DE",
    "temp": 9
  },
  {
    "name": "Noervenich (AFB), NT, DE",
    "temp": 10
  },
  {
    "name": "Laage Arpt, MV, DE",
    "temp": 11
  },
  {
    "name": "Hohn (AFB), SH, DE",
    "temp": 8
  },
  {
    "name": "Nordholz Arpt(NAVY), NI, DE",
    "temp": 9
  },
  {
    "name": "Fassberg Arpt(AFB), NI, DE",
    "temp": 8
  },
  {
    "name": "Niederstetten Arpt, BW, DE",
    "temp": 7
  },
  {
    "name": "Laupheim Arpt(AAF), BW, DE",
    "temp": 9
  },
  {
    "name": "Fritzlar Arpt(AAF), HE, DE",
    "temp": 8
  },
  {
    "name": "Celle Arpt(AAF), NI, DE",
    "temp": 8
  },
  {
    "name": "Bückeburg(AAF), NI, DE",
    "temp": 9
  },
  {
    "name": "Altenstadt(AB), BY, DE",
    "temp": 9
  },
  {
    "name": "Gluecksburg/Meierwik, SH, DE",
    "temp": 9
  },
  {
    "name": "Hamavan Arpt, AC, SE",
    "temp": 5
  },
  {
    "name": "Pajala Arpt, BD, SE",
    "temp": 6
  },
  {
    "name": "Llungbyhed Arpt, M, SE",
    "temp": 15
  },
  {
    "name": "Angelholm Arpt, M, SE",
    "temp": 12
  },
  {
    "name": "Visby Arpt, I, SE",
    "temp": 7
  },
  {
    "name": "Torsby Arpt, S, SE",
    "temp": 16
  },
  {
    "name": "Norrköping Arpt, E, SE",
    "temp": 11
  },
  {
    "name": "Linköping City Arpt, E, SE",
    "temp": 12
  },
  {
    "name": "Borlange/Dala Arpt, W, SE",
    "temp": 14
  },
  {
    "name": "Stockholm/Bromma Arpt, AB, SE",
    "temp": 11
  },
  {
    "name": "Stockholm/Arlanda Arpt, AB, SE",
    "temp": 9
  },
  {
    "name": "Vidsel(AFB), BD, SE",
    "temp": 12
  },
  {
    "name": "Luleå Arpt, BD, SE",
    "temp": 8
  },
  {
    "name": "Stockholm/Västerås Arpt, U, SE",
    "temp": 12
  },
  {
    "name": "Karlstad Arpt, S, SE",
    "temp": 12
  },
  {
    "name": "Örebro Arpt, T, SE",
    "temp": 13
  },
  {
    "name": "Are Ostersund Arpt, Z, SE",
    "temp": 10
  },
  {
    "name": "Arvidsjaur Arpt, BD, SE",
    "temp": 9
  },
  {
    "name": "Vilhelmina Arpt, AC, SE",
    "temp": 11
  },
  {
    "name": "Umeå Arpt, AC, SE",
    "temp": 6
  },
  {
    "name": "Skellefteå Arpt, AC, SE",
    "temp": 11
  },
  {
    "name": "Kiruna Arpt, BD, SE",
    "temp": 6
  },
  {
    "name": "Örnsköldsvik Arpt, Y, SE",
    "temp": 7
  },
  {
    "name": "Sundsvall-Timra Aprt, Y, SE",
    "temp": 9
  },
  {
    "name": "Lycksele Arpt, AC, SE",
    "temp": 11
  },
  {
    "name": "Kramfors/Solleftea Arpt, Y, SE",
    "temp": 8
  },
  {
    "name": "Gällivare Arpt, BD, SE",
    "temp": 0
  },
  {
    "name": "Sveg Arpt, Z, SE",
    "temp": 13
  },
  {
    "name": "Växjö Arpt, G, SE",
    "temp": 18
  },
  {
    "name": "Hagshult(AFB), F, SE",
    "temp": 18
  },
  {
    "name": "Halmstad Arpt, N, SE",
    "temp": 15
  },
  {
    "name": "Malmo/Sturup Arpt, M, SE",
    "temp": 18
  },
  {
    "name": "Kalmar Arpt, H, SE",
    "temp": 12
  },
  {
    "name": "Kristianstad Arpt, S, SE",
    "temp": 15
  },
  {
    "name": "Salen/Scandanavian Mtns Arpt, W, SE",
    "temp": 13
  },
  {
    "name": "Stockholm/Skavsta Arpt, D, SE",
    "temp": 11
  },
  {
    "name": "Mora-Siljan Arpt, W, SE",
    "temp": 12
  },
  {
    "name": "Satenas Arpt, O, SE",
    "temp": 13
  },
  {
    "name": "Karlsborg (AFB), O, SE",
    "temp": 12
  },
  {
    "name": "Trollhattan Arpt, O, SE",
    "temp": 15
  },
  {
    "name": "Goteborg/City Arpt, O, SE",
    "temp": 9
  },
  {
    "name": "Jönköping Arpt, F, SE",
    "temp": 15
  },
  {
    "name": "Goteborg/Landvetter Arpt, O, SE",
    "temp": 13
  },
  {
    "name": "Ronneby Arpt, K, SE",
    "temp": 19
  },
  {
    "name": "Uppsala Arpt, C, SE",
    "temp": 11
  },
  {
    "name": "Linkoping/Malmen Arpt, E, SE",
    "temp": 11
  },
  {
    "name": "Stavanger/Sola Arpt, RO, NO",
    "temp": 10
  },
  {
    "name": "Valhall, --, NO",
    "temp": 10
  },
  {
    "name": "Vadsø Arpt, FI, NO",
    "temp": 1
  },
  {
    "name": "Trondheim Arpt, TR, NO",
    "temp": 13
  },
  {
    "name": "Nord B, --, NO",
    "temp": 8
  },
  {
    "name": "Goliat, --, NO",
    "temp": 1
  },
  {
    "name": "Torp Arpt, VE, NO",
    "temp": 14
  },
  {
    "name": "Tromsø Arpt, TR, NO",
    "temp": 2
  },
  {
    "name": "Sandnessjøen Arpt, NO, NO",
    "temp": 8
  },
  {
    "name": "Vardoe Arpt, FI, NO",
    "temp": 3
  },
  {
    "name": "Sørkjosen Arpt, TR, NO",
    "temp": 4
  },
  {
    "name": "Sleipner A Plat, --, NO",
    "temp": 9
  },
  {
    "name": "Storkmarknes Arpt, NO, NO",
    "temp": 6
  },
  {
    "name": "Svolvaer/Helle Arpt, NO, NO",
    "temp": 6
  },
  {
    "name": "Sogndal/Haukasen Arpt, SO, NO",
    "temp": 8
  },
  {
    "name": "Statfjord A, --, NO",
    "temp": 7
  },
  {
    "name": "Snorre A, --, NO",
    "temp": 9
  },
  {
    "name": "Sandane Arpt, SO, NO",
    "temp": 10
  },
  {
    "name": "Longyearbyen/Svalbard Arpt, SV, SJ",
    "temp": -5
  },
  {
    "name": "Moss/Rygge Arpt, OS, NO",
    "temp": 14
  },
  {
    "name": "Røst Arpt(AFB), VE, NO",
    "temp": 7
  },
  {
    "name": "Røros Arpt, TR, NO",
    "temp": 9
  },
  {
    "name": "Rørvik Arpt, TR, NO",
    "temp": 9
  },
  {
    "name": "Moirana Arpt, NO, NO",
    "temp": 6
  },
  {
    "name": "Snorre B, --, NO",
    "temp": 8
  },
  {
    "name": "Troll-C, --, NO",
    "temp": 12
  },
  {
    "name": "Troll-A, --, NO",
    "temp": 9
  },
  {
    "name": "Ørsta-Volda Arpt, MR, NO",
    "temp": 8
  },
  {
    "name": "Ørland Arpt, TR, NO",
    "temp": 9
  },
  {
    "name": "Oseberg, --, NO",
    "temp": 7
  },
  {
    "name": "Namsos Arpt, TR, NO",
    "temp": 9
  },
  {
    "name": "Norne, --, NO",
    "temp": 7
  },
  {
    "name": "Banak Arpt, FI, NO",
    "temp": 1
  },
  {
    "name": "Mosjøen Arpt, NO, NO",
    "temp": 9
  },
  {
    "name": "Molde/Aro Arpt, MR, NO",
    "temp": 11
  },
  {
    "name": "Mehamn Arpt, FI, NO",
    "temp": 1
  },
  {
    "name": "Leknes Arpt, NO, NO",
    "temp": 5
  },
  {
    "name": "Ekofisk, --, NO",
    "temp": 8
  },
  {
    "name": "Ula, --, NO",
    "temp": 14
  },
  {
    "name": "Kirkenes/Høybuktmoen Arpt, FI, NO",
    "temp": 2
  },
  {
    "name": "Kristiansund Arpt, MR, NO",
    "temp": 8
  },
  {
    "name": "Johan Sverdrup, --, NO",
    "temp": 10
  },
  {
    "name": "Honningsvag/Valan Arpt, SV, SJ",
    "temp": 2
  },
  {
    "name": "Hasvik Arpt, FI, NO",
    "temp": 2
  },
  {
    "name": "Hammerfest Arpt, FI, NO",
    "temp": 1
  },
  {
    "name": "Heidrun, --, NO",
    "temp": 7
  },
  {
    "name": "Haugesund Arpt, RO, NO",
    "temp": 10
  },
  {
    "name": "Oslo/Gardermoen Arpt, AK, NO",
    "temp": 14
  },
  {
    "name": "Florø Arpt, SO, NO",
    "temp": 9
  },
  {
    "name": "Statford B, --, NO",
    "temp": 8
  },
  {
    "name": "Evenes Arpt, TR, NO",
    "temp": 5
  },
  {
    "name": "Bardufoss Arpt, TR, NO",
    "temp": 0
  },
  {
    "name": "Draugen, --, NO",
    "temp": 7
  },
  {
    "name": "Kristiansand Arpt, VA, NO",
    "temp": 14
  },
  {
    "name": "Berlevåg Arpt, FI, NO",
    "temp": 1
  },
  {
    "name": "Båtsfjord Arpt, FI, NO",
    "temp": 0
  },
  {
    "name": "Bergen/Flesland Arpt, HO, NO",
    "temp": 9
  },
  {
    "name": "Bodø Arpt, NO, NO",
    "temp": 6
  },
  {
    "name": "Bronnoysund/Bronnoy Arpt, NO, NO",
    "temp": 8
  },
  {
    "name": "Forde/Bringeland Arpt, SO, NO",
    "temp": 7
  },
  {
    "name": "Alta Arpt, FI, NO",
    "temp": 3
  },
  {
    "name": "Andøya Arpt, NO, NO",
    "temp": 4
  },
  {
    "name": "Vigra/Alesund Arpt, MR, NO",
    "temp": 9
  },
  {
    "name": "Luxembourg/Findel Arpt, LL, LU",
    "temp": 8
  },
  {
    "name": "Aalborg Arpt, NO, DK",
    "temp": 9
  },
  {
    "name": "Stauning Arpt, MI, DK",
    "temp": 9
  },
  {
    "name": "Sørvágur/Vágar Arpt, VG, DK",
    "temp": 4
  },
  {
    "name": "Vojens Arpt(AFB), SY, DK",
    "temp": 9
  },
  {
    "name": "Sønderborg Arpt, SY, DK",
    "temp": 9
  },
  {
    "name": "Ronne/Bornholm Arpt, HO, DK",
    "temp": 11
  },
  {
    "name": "Koebenhavn/Roskilde Arpt, SJ, DK",
    "temp": 11
  },
  {
    "name": "Odense Arpt, SY, DK",
    "temp": 9
  },
  {
    "name": "Karup Arpt, MI, DK",
    "temp": 9
  },
  {
    "name": "Esbjerg Arpt, SY, DK",
    "temp": 9
  },
  {
    "name": "Kobenhavn Intl, HO, DK",
    "temp": 11
  },
  {
    "name": "Billund Arpt, SY, DK",
    "temp": 9
  },
  {
    "name": "Tirstrup Arpt, MI, DK",
    "temp": 8
  },
  {
    "name": "Northolt(RAF), EN, GB",
    "temp": 17
  },
  {
    "name": "Brize Norton(RAF), EN, GB",
    "temp": 13
  },
  {
    "name": "Oxford Arpt, EN, GB",
    "temp": 14
  },
  {
    "name": "Exeter Arpt, EN, GB",
    "temp": 10
  },
  {
    "name": "Cranfield Arpt, EN, GB",
    "temp": 15
  },
  {
    "name": "St Athan Arpt, WL, GB",
    "temp": 10
  },
  {
    "name": "London/Stansted Arpt, EN, GB",
    "temp": 16
  },
  {
    "name": "Norwich Intl, EN, GB",
    "temp": 15
  },
  {
    "name": "Cambridge Arpt, EN, GB",
    "temp": 17
  },
  {
    "name": "Tiree Island Arpt, SC, GB",
    "temp": 10
  },
  {
    "name": "Stornoway Arpt, SC, GB",
    "temp": 9
  },
  {
    "name": "Dundee Arpt, SC, GB",
    "temp": 9
  },
  {
    "name": "Prestwick Intl, SC, GB",
    "temp": 11
  },
  {
    "name": "Islay Arpt, SC, GB",
    "temp": 8
  },
  {
    "name": "Edinburgh Arpt, SC, GB",
    "temp": 9
  },
  {
    "name": "Glasgow Arpt, SC, GB",
    "temp": 9
  },
  {
    "name": "Inverness Arpt, SC, GB",
    "temp": 9
  },
  {
    "name": "Aberdeen Arpt, SC, GB",
    "temp": 10
  },
  {
    "name": "Wick Arpt, SC, GB",
    "temp": 9
  },
  {
    "name": "Sumburgh Arpt, SC, GB",
    "temp": 9
  },
  {
    "name": "Kirkwall Arpt, SC, GB",
    "temp": 9
  },
  {
    "name": "Nottingham/E Midlands Arpt, EN, GB",
    "temp": 15
  },
  {
    "name": "Teesside Intl, EN, GB",
    "temp": 13
  },
  {
    "name": "Newcastle Intl, SC, GB",
    "temp": 10
  },
  {
    "name": "Isle Of Man Arpt, --, IM",
    "temp": 10
  },
  {
    "name": "Hawarden Arpt, WL, GB",
    "temp": 11
  },
  {
    "name": "Leeds Bradford Intl, EN, GB",
    "temp": 12
  },
  {
    "name": "Humberside Intl, EN, GB",
    "temp": 14
  },
  {
    "name": "Blackpool Arpt, EN, GB",
    "temp": 13
  },
  {
    "name": "Lydd Arpt, EN, GB",
    "temp": 16
  },
  {
    "name": "Southend Arpt, EN, GB",
    "temp": 16
  },
  {
    "name": "London/Heathrow Intl, EN, GB",
    "temp": 16
  },
  {
    "name": "Farnborough Arpt, EN, GB",
    "temp": 14
  },
  {
    "name": "London City Arpt, EN, GB",
    "temp": 16
  },
  {
    "name": "London/Gatwick Arpt, EN, GB",
    "temp": 15
  },
  {
    "name": "London/Biggin Hill Arpt, EN, GB",
    "temp": 14
  },
  {
    "name": "Shoreham Arpt, EN, GB",
    "temp": 13
  },
  {
    "name": "Jersey Arpt, --, JE",
    "temp": 10
  },
  {
    "name": "Guernsey Arpt, --, GG",
    "temp": 10
  },
  {
    "name": "Alderney Arpt, --, GG",
    "temp": 10
  },
  {
    "name": "Newquay/Cornwall Arpt, EN, GB",
    "temp": 13
  },
  {
    "name": "Southampton Intl, EN, GB",
    "temp": 12
  },
  {
    "name": "Bournemouth Intl, EN, GB",
    "temp": 10
  },
  {
    "name": "Scilly Isles/St Marys Arpt, EN, GB",
    "temp": 13
  },
  {
    "name": "Penzance/Lands End Arpt, EN, GB",
    "temp": 13
  },
  {
    "name": "Luton Arpt, EN, GB",
    "temp": 14
  },
  {
    "name": "Liverpool/Lennon Arpt, EN, GB",
    "temp": 12
  },
  {
    "name": "Bristol Intl, EN, GB",
    "temp": 9
  },
  {
    "name": "Cardiff Intl, WL, GB",
    "temp": 9
  },
  {
    "name": "Oban Arpt, SC, GB",
    "temp": 12
  },
  {
    "name": "Campbeltown Arpt, SC, GB",
    "temp": 9
  },
  {
    "name": "Caernarfon Arpt, WL, GB",
    "temp": 11
  },
  {
    "name": "Manchester Intl, EN, GB",
    "temp": 13
  },
  {
    "name": "Gloucestershire Arpt, EN, GB",
    "temp": 13
  },
  {
    "name": "Birmingham Intl, EN, GB",
    "temp": 14
  },
  {
    "name": "Derry/City Arpt, NI, GB",
    "temp": 8
  },
  {
    "name": "Belfast/City Arpt, NI, GB",
    "temp": 8
  },
  {
    "name": "Belfast Intl, NI, GB",
    "temp": 8
  },
  {
    "name": "Vaasa Arpt, PO, FI",
    "temp": 11
  },
  {
    "name": "Utti Arpt, KY, FI",
    "temp": 14
  },
  {
    "name": "Turku Arpt, VS, FI",
    "temp": 17
  },
  {
    "name": "Tampere/Pirkkala Arpt, PI, FI",
    "temp": 14
  },
  {
    "name": "Seinajoki/Ilmajoki Arpt, EP, FI",
    "temp": 11
  },
  {
    "name": "Savonlinna Arpt, ES, FI",
    "temp": 13
  },
  {
    "name": "Rovaniemi Arpt, LL, FI",
    "temp": 6
  },
  {
    "name": "Pori Arpt, EK, FI",
    "temp": 15
  },
  {
    "name": "Oulu Arpt, PP, FI",
    "temp": 10
  },
  {
    "name": "Mikkeli Arpt, ES, FI",
    "temp": 13
  },
  {
    "name": "Mariehamn Arpt, AH, FI",
    "temp": 9
  },
  {
    "name": "Lappeenranta Arpt, EK, FI",
    "temp": 15
  },
  {
    "name": "Kuopio Arpt, PS, FI",
    "temp": 11
  },
  {
    "name": "Kittilä Arpt, LL, FI",
    "temp": 5
  },
  {
    "name": "Kuusamo Arpt, PP, FI",
    "temp": 7
  },
  {
    "name": "Kruunupyy Arpt, KP, FI",
    "temp": 12
  },
  {
    "name": "Kajaani Arpt, PP, FI",
    "temp": 10
  },
  {
    "name": "Kemi/Tornio Arpt, LL, FI",
    "temp": 3
  },
  {
    "name": "Jyväskylä Arpt, KS, FI",
    "temp": 11
  },
  {
    "name": "Joensuu Arpt, PK, FI",
    "temp": 11
  },
  {
    "name": "Ivalo Arpt, LL, FI",
    "temp": 7
  },
  {
    "name": "Helsinki/Vantaa Arpt, UU, FI",
    "temp": 12
  },
  {
    "name": "Halli Arpt, KS, FI",
    "temp": 11
  },
  {
    "name": "Enontekio Arpt, LL, FI",
    "temp": 4
  },
  {
    "name": "Tartu Arpt, TA, EE",
    "temp": 21
  },
  {
    "name": "Tallin Arpt, HA, EE",
    "temp": 22
  },
  {
    "name": "Pärnu Arpt, PA, EE",
    "temp": 24
  },
  {
    "name": "Kuressaare Arpt, SA, EE",
    "temp": 14
  },
  {
    "name": "Kärdla Arpt, HI, EE",
    "temp": 21
  },
  {
    "name": "Westerland/Sylt Arpt, SH, DE",
    "temp": 8
  },
  {
    "name": "Emden Arpt, NI, DE",
    "temp": 10
  },
  {
    "name": "Kassel/Calden Arpt, HE, DE",
    "temp": 7
  },
  {
    "name": "Braunschweig Arpt, NI, DE",
    "temp": 9
  },
  {
    "name": "Schwäbisch Hall Arpt, BW, DE",
    "temp": 7
  },
  {
    "name": "Lahr/Black Forest Arpt, BW, DE",
    "temp": 9
  },
  {
    "name": "Baden Arpt, BW, DE",
    "temp": 9
  },
  {
    "name": "Hof/Plauen Arpt, BY, DE",
    "temp": 6
  },
  {
    "name": "Friedrichshafen Arpt, BW, DE",
    "temp": 10
  },
  {
    "name": "Oberpfaffenhofen Arpt, BY, DE",
    "temp": 9
  },
  {
    "name": "Augsberg Arpt, BY, DE",
    "temp": 9
  },
  {
    "name": "Dortmund Arpt, NT, DE",
    "temp": 9
  },
  {
    "name": "Weeze Arpt, NT, DE",
    "temp": 11
  },
  {
    "name": "Paderborn Arpt, NT, DE",
    "temp": 7
  },
  {
    "name": "Monchengladbach Arpt, NW, DE",
    "temp": 11
  },
  {
    "name": "Memmingerberg Arpt, BY, DE",
    "temp": 9
  },
  {
    "name": "Lübeck Arpt, SH, DE",
    "temp": 8
  },
  {
    "name": "Kiel/Holtenau Arpt, SH, DE",
    "temp": 9
  },
  {
    "name": "Hamburg/FinkenwerderR Arpt, HH, DE",
    "temp": 9
  },
  {
    "name": "Siegerland Arpt, NT, DE",
    "temp": 5
  },
  {
    "name": "Mannheim City Arpt, BW, DE",
    "temp": 9
  },
  {
    "name": "Frankfurt/Hahn Arpt, RP, DE",
    "temp": 6
  },
  {
    "name": "Bremen Arpt, HB, DE",
    "temp": 10
  },
  {
    "name": "Hannover Arpt, NI, DE",
    "temp": 8
  },
  {
    "name": "Stuttgart Arpt, BW, DE",
    "temp": 8
  },
  {
    "name": "Saarbrücken Arpt, SL, DE",
    "temp": 8
  },
  {
    "name": "Leipzig/Halle Arpt, SN, DE",
    "temp": 10
  },
  {
    "name": "Nurnberg Arpt, BY, DE",
    "temp": 10
  },
  {
    "name": "Munich Intl, BY, DE",
    "temp": 10
  },
  {
    "name": "Düsseldorf Intl, NT, DE",
    "temp": 12
  },
  {
    "name": "Koln-Bonn Arpt, NT, DE",
    "temp": 10
  },
  {
    "name": "Hamburg Arpt, HH, DE",
    "temp": 9
  },
  {
    "name": "Münster/Osnabrück Arpt, NT, DE",
    "temp": 10
  },
  {
    "name": "Frankfurt/Main Arpt, HE, DE",
    "temp": 10
  },
  {
    "name": "Erfurt Arpt, TH, DE",
    "temp": 8
  },
  {
    "name": "Dresden Arpt, SN, DE",
    "temp": 9
  },
  {
    "name": "Berlin/Brandenburg Intl, BR, DE",
    "temp": 12
  },
  {
    "name": "Magdeburg/Cochstedt Arpt, ST, DE",
    "temp": 9
  },
  {
    "name": "Heringsdorf Arpt, MV, DE",
    "temp": 12
  },
  {
    "name": "Altenburg Arpt, ID, DE",
    "temp": 9
  },
  {
    "name": "Oostende-Bruges Intl, VH, BE",
    "temp": 17
  },
  {
    "name": "Bierset/Liège Arpt, WL, BE",
    "temp": 10
  },
  {
    "name": "Charleroi Arpt, WH, BE",
    "temp": 14
  },
  {
    "name": "Brussels Intl, VL, BE",
    "temp": 15
  },
  {
    "name": "Antwerp Intl, VA, BE",
    "temp": 14
  },
  {
    "name": "Gore Bay/Manitoulin Arpt, ON, CA",
    "temp": 5
  },
  {
    "name": "Thompson Arpt, MB, CA",
    "temp": -15
  },
  {
    "name": "Puvungnituq Arpt, QC, CA",
    "temp": -6
  },
  {
    "name": "Bella Bella Arpt, BC, CA",
    "temp": 3
  },
  {
    "name": "Stroemfjord Arpt, QQ, GL",
    "temp": -7
  },
  {
    "name": "Godthab/Nuuk Arpt, SM, GL",
    "temp": 2
  },
  {
    "name": "Novosibirsk/Tolmachevo Arpt, NV, RU",
    "temp": 1
  },
  {
    "name": "Buenos Aires/Pistarini Arpt, B, AR",
    "temp": 13
  },
  {
    "name": "Elim Arpt, AK, US",
    "temp": 0
  },
  {
    "name": "Taylorville Muni, IL, US",
    "temp": 16
  },
  {
    "name": "Marysville/Union Cnty, OH, US",
    "temp": 13
  },
  {
    "name": "Harlingen/Valley Intl, TX, US",
    "temp": 23.9
  },
  {
    "name": "Air Force Academy Arfld, CO, US",
    "temp": -2
  },
  {
    "name": "Winnipeg Intl Arpt, MB, CA",
    "temp": -1
  },
  {
    "name": "Gjoa Haven Arpt, NU, CA",
    "temp": -23
  },
  {
    "name": "Anaktuvuk Pass Arpt, AK, US",
    "temp": -7
  },
  {
    "name": "Igiugig Arpt, AK, US",
    "temp": -1
  },
  {
    "name": "Siloam Springs/Smith Fld, AR, US",
    "temp": 19
  },
  {
    "name": "Sheridan Cnty Arpt, WY, US",
    "temp": -1.7
  },
  {
    "name": "Ely/Yelland Fld, NV, US",
    "temp": -2.2
  },
  {
    "name": "Mobile/Downtown Arpt, AL, US",
    "temp": 19.4
  },
  {
    "name": "Andalusia/Benton Fld, AL, US",
    "temp": 11.7
  },
  {
    "name": "Selawik Arpt, AK, US",
    "temp": -2
  },
  {
    "name": "Homer Arpt, AK, US",
    "temp": 2.8
  },
  {
    "name": "Culiacan Intl, SI, MX",
    "temp": 18
  },
  {
    "name": "Terrell Muni, TX, US",
    "temp": 20
  },
  {
    "name": "Mc Gregor Exec, TX, US",
    "temp": 0
  },
  {
    "name": "Ontario Intl, CA, US",
    "temp": 12.2
  },
  {
    "name": "Marshfield Muni, WI, US",
    "temp": 9.4
  },
  {
    "name": "Wisconsin Rapids/S Wood Cnty, WI, US",
    "temp": 9.4
  },
  {
    "name": "Dubois Muni, WY, US",
    "temp": -8
  },
  {
    "name": "Denver Intl, CO, US",
    "temp": -1.7
  },
  {
    "name": "Cheyenne Rgnl, WY, US",
    "temp": -5
  },
  {
    "name": "Cody/Yellowstone Rgnl, WY, US",
    "temp": -3
  },
  {
    "name": "Melbourne Intl, VI, AU",
    "temp": 17
  },
  {
    "name": "Kuala Lumpur/Shah Arpt, SL, MY",
    "temp": 31
  },
  {
    "name": "Puerto Maldonado Arpt, MD, PE",
    "temp": 23
  },
  {
    "name": "Iquitos/Vignetta Arpt, LO, PE",
    "temp": 23
  },
  {
    "name": "Kwethluk Arpt, AK, US",
    "temp": -4
  },
  {
    "name": "Shemya/Eareckson Arpt, AK, US",
    "temp": 3
  },
  {
    "name": "Kotzebue/Wien Mem, AK, US",
    "temp": -6.1
  },
  {
    "name": "Metlakatla, AK, US",
    "temp": 7
  },
  {
    "name": "Enid/Woodring Arpt, OK, US",
    "temp": 20
  },
  {
    "name": "Paynesville Muni, MN, US",
    "temp": 5
  },
  {
    "name": "Wilcox/Chocise Cnty, AZ, US",
    "temp": 10
  },
  {
    "name": "San Nicholas Island Arpt, CA, US",
    "temp": 11.1
  },
  {
    "name": "Monarch Pass, CO, US",
    "temp": -7
  },
  {
    "name": "Midland/Barstow Fld, MI, US",
    "temp": 9
  },
  {
    "name": "Batavia/Clermont Cnty, OH, US",
    "temp": 18.8
  },
  {
    "name": "Gatlinburg-Pigeon Forge Arpt, TN, US",
    "temp": 6
  },
  {
    "name": "Flag Island, MN, US",
    "temp": 0
  },
  {
    "name": "Emporia Muni, KS, US",
    "temp": 15.6
  },
  {
    "name": "Black River Falls Arpt, WI, US",
    "temp": 10.5
  },
  {
    "name": "Altus/Quartz Mtn Rgnl, OK, US",
    "temp": 20
  }
];